sudo: false
language: python
cache: pip
before_cache:
  - rm -f $HOME/.cache/pip/log/debug.log
branches:
  except:
    - /^WIP-.*$/
python:
  - "3.6"
  - "3.7"
install:
  - pip install tox-travis
script:
  - tox
